import 'package:coding_challenge_2/src/servus_flutter/app/coding_challenge_app.dart';
import 'package:coding_challenge_2/src/servus_flutter/widgets/challenge_explanation.dart';
import 'package:coding_challenge_2/src/servus_flutter/widgets/challenge_tester.dart';
import 'package:coding_challenge_2/src/servus_flutter/widgets/painted_test_box.dart';
import 'package:coding_challenge_2/src/servus_flutter/widgets/sized_test_box.dart';
import 'package:coding_challenge_2/start_widget.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

///
/// Please do not edit this file!!!
///
/// Go to this file to start the coding challenge [start_widget.dart]
///
class CodingChallengeWrapper extends StatelessWidget {
  final GlobalKey challengerWidgetKey = GlobalKey();

  final String testId;

  CodingChallengeWrapper({
    super.key,
    required this.testId,
  });

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      child: CodingChallengeApp(
          child: SingleChildScrollView(
        child: Center(
          child: Column(
            children: [
              const ChallengeExplanation(),
              const SizedBox(height: 16),
              SizedTestBox(
                child: PaintedTestBox(
                    challengerWidgetKey: challengerWidgetKey,
                    challengerWidget: const StartWidget()),
              ),
              ChallengeTester(
                challengerWidgetKey: challengerWidgetKey,
                testId: testId,
              ),
              const SizedBox(height: 80),
            ],
          ),
        ),
      )),
    );
  }
}
