import 'package:coding_challenge_1/servus_flutter/servus_flutter_main.dart';
import 'package:flutter/material.dart';

///
/// Please do not edit this file!!!
///
/// Go to this file to start the coding challenge [start_widget.dart]
///
void main() {
  runApp(const ServusFlutterMain());
}
