import 'package:coding_challenge_1/src/servus_flutter/coding_challenge_wrapper.dart';
import 'package:flutter/material.dart';

///
/// Please do not edit this file!!!
///
/// Go to this file to start the coding challenge [start_widget.dart]
///
void main() {
  runApp(CodingChallengeWrapper());
}
